version: '3'
services:
  client-gateway:
    build: ./client-gateway
    ports:
      - "5001:5001"
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - NODE_ENV=development
      - PORT=5001
      - BINANCE_MICROSERVICE_HOST=binance-accounts
      - BINANCE_MICROSERVICE_PORT=5002
    depends_on:
      - binance-accounts
    networks:
      - bunker-network
  binance-accounts:
    build: ./binance-accounts-ms
    ports:
      - "5002:5002"
    volumes:
      - ./binance-accounts-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - NODE_ENV=development
      - PORT=5002
      - DATABASE_DIALECT=postgres
      - DATABASE_URI=${DATABASE_URI}
      - ADMIN_PORT=5000
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - AWS_ACCESS_KEY_ID=AKIAYQNJSKG2HOB54WIC
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_REGION=us-east-1
    networks:
      - bunker-network

  # postgres:
  #   image: postgres:16-alpine
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=1234
  #     - POSTGRES_DB=bunker
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - bunker-network

# volumes:
#   postgres_data:

networks:
  bunker-network:
    driver: bridge

